# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods_sort',
            table='goods_sort',
        ),
    ]
