# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0002_auto_20191108_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_sort',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='删除'),
        ),
        migrations.AlterModelTable(
            name='goods_info',
            table='goods_info',
        ),
    ]
