# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0003_auto_20191109_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_info',
            name='number',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
