# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0004_goods_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='area',
            field=models.CharField(default='', max_length=50, verbose_name='产地'),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='remark',
            field=models.CharField(default='', max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='spec',
            field=models.CharField(default='', max_length=50, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='unit',
            field=models.CharField(default='', max_length=50, verbose_name='单位'),
        ),
    ]
