# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0005_auto_20191111_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_info',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='删除'),
        ),
    ]
